# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authenticator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=30)),
                ('PassWord', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SecurityType', models.CharField(max_length=3)),
                ('Amount', models.FloatField()),
                ('Cost', models.FloatField()),
                ('RateOfChange', models.DecimalField(decimal_places=3, max_digits=3)),
                ('Confidence', models.DecimalField(decimal_places=3, max_digits=3)),
                ('TimeOf', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SecurityType', models.CharField(max_length=3)),
                ('Amount', models.FloatField()),
                ('ProfitPercent', models.FloatField()),
                ('RateOfChange', models.FloatField()),
                ('Confidence', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
        ),
    ]
