# Generated by Django 2.0.2 on 2018-03-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketAction', models.CharField(max_length=4)),
                ('primarySecurity', models.CharField(max_length=4)),
                ('secondarySecurity', models.CharField(max_length=4)),
                ('receivedAmount', models.DecimalField(decimal_places=18, max_digits=18)),
                ('givenAmount', models.DecimalField(decimal_places=18, max_digits=18)),
                ('date', models.DateField()),
                ('currentExposure', models.FloatField()),
                ('misc', models.CharField(max_length=200)),
            ],
        ),
    ]
