# Generated by Django 2.0.3 on 2018-03-29 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketPair', models.CharField(max_length=40)),
                ('currentExposure', models.DecimalField(decimal_places=18, max_digits=36)),
                ('miscellaneous', models.CharField(max_length=1000)),
                ('userId', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionId', models.CharField(max_length=40)),
                ('marketPair', models.CharField(max_length=40)),
                ('marketAction', models.CharField(max_length=4)),
                ('primarySecurity', models.CharField(max_length=4)),
                ('secondarySecurity', models.CharField(max_length=4)),
                ('receivedAmount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('givenAmount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('date', models.DateField()),
                ('userId', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
