# Generated by Django 2.0.2 on 2018-03-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoonMachine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='currentExposure',
            field=models.DecimalField(decimal_places=18, max_digits=36),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='givenAmount',
            field=models.DecimalField(decimal_places=18, max_digits=36),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receivedAmount',
            field=models.DecimalField(decimal_places=18, max_digits=36),
        ),
    ]
