# Generated by Django 2.0.2 on 2018-03-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoonMachine', '0002_DoubledMaxDigits'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='market',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
